api = "0.6"

[buildpack]
id = "heroku/nodejs-npm"
version = "0.4.5"
name = "NPM Buildpack"
keywords = ["nodejs", "node", "npm"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "*"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-npm-buildpack"
