[package]
name = "heroku-nodejs-engine-buildpack"
version = "0.8.0"
edition = "2021"

[dependencies]
libcnb = { git = "https://github.com/Malax/libcnb.rs" }
libcnb-nodejs = { path = "../../libcnb-nodejs" }
serde = "1.0.136"
flate2 = "1.0.22"
sha2 = "0.10.1"
ureq = "2.4.0"
tar = "0.4.38"
tempfile = "3.3.0"
toml = "0.5"

[dev-dependencies]
libcnb-test = { git = "https://github.com/Malax/libcnb.rs" }
